Header page
Lebanon-WBC-Capstones/e-track-web pull request #17
Opened 2021-02-13 14:40 UTC by Abdellatif-E

2021-02-13 16:33 UTC, osamaakb requested changes
Good Job abdellatif, make sure you have the latest master version cause the About is in your PR but its already in the master so sync it again and push + check the comments too

2021-02-13 16:33 UTC, osamaakb commented on src/Pages/HomePage/Header/Header.js
> +        alt=""
added alt text here

2021-02-13 16:33 UTC, osamaakb commented on src/Pages/HomePage/Header/Header.js
> +          </span>{' '}
remove these `{'  '}`

2021-02-13 16:33 UTC, osamaakb commented on .eslintcache
> +[{"D:\\uni\\workshop\\2020 Re-Coded\\Capstone project\\e-track-web\\src\\index.js":"1","D:\\uni\\workshop\\2020 Re-Coded\\Capstone project\\e-track-web\\src\\App.js":"2","D:\\uni\\workshop\\2020 Re-C
don't commit this file

2021-02-13 18:01 UTC, Abdellatif-E commented
All done i added the alt text , removed the unneeded symbols also i did git fetch and pull so it's up-to-date
thank you osama for feedback

2021-02-14 09:03 UTC, osamaakb requested changes

2021-02-14 09:03 UTC, osamaakb commented on .eslintcache
> +[{"D:\\uni\\workshop\\2020 Re-Coded\\Capstone project\\e-track-web\\src\\index.js":"1","D:\\uni\\workshop\\2020 Re-Coded\\Capstone project\\e-track-web\\src\\App.js":"2","D:\\uni\\workshop\\2020 Re-C
can you not commit this one?

2021-02-14 09:03 UTC, osamaakb commented on src/App.js
>  function App() {
make your app.js similar to the one on master

2021-02-15 07:43 UTC, osamaakb approved these changes

2021-02-15 07:43 UTC, merged