Dashboard page
Lebanon-WBC-Capstones/e-track-web pull request #48
Opened 2021-02-25 21:59 UTC by JanaKhanji

I had to change some stuff in the components.
also please check the data.js

2021-02-26 06:22 UTC, JanaKhanji commented on src/data.js
> +    ongoing: true,
make it completed instead of ongoing

2021-02-26 06:32 UTC, JanaKhanji commented on src/Components/Dashboard/Tracker/Tracker.js
> +    today = tracker.track.filter(
const today !!!

2021-02-26 19:26 UTC, osamaakb requested changes
Good job @JanaKhanji , this looks really nice, 2 quick comments I have, 
Then Navbar background doesn't match the rest of the page, see the image below

![image](https://user-images.githubusercontent.com/12795240/109345735-a20ff080-7881-11eb-9841-812f8a03ca64.png)

And the page has some vertical scrolling, can we have it not scrollable?

2021-02-26 19:56 UTC, JanaKhanji commented
I don't think we can have it without the vertical scrolling because the components in the first column are large and they didn't fit.
also for the light grey background, the navbar is a global component so it is in the app next to the dashboard page, and the background should be applied to the whole app style because it is the color of all the pages so I didn't do it here

2021-02-26 19:57 UTC, JanaKhanji commented
should I remove the weather component to prevent the scrolling?

2021-02-27 09:19 UTC, osamaakb commented
> should I remove the weather component to prevent the scrolling?

if that will fix the problem, it's better to remove it then

2021-02-27 09:20 UTC, osamaakb commented
> I don't think we can have it without the vertical scrolling because the components in the first column are large and they didn't fit.
> also for the light grey background, the navbar is a global component so it is in the app next to the dashboard page, and the background should be applied to the whole app style because it is the color of all the pages so I didn't do it here

can you then make it's background transparent or something to take the background of the app, cause it doesn't look really good like this

2021-02-27 09:56 UTC, JanaKhanji commented
> > should I remove the weather component to prevent the scrolling?
> 
> if that will fix the problem, it's better to remove it then

2021-02-27 09:56 UTC, closed without merging