Collection branch
Lebanon-WBC-Capstones/e-track-web pull request #72
Opened 2021-03-03 19:20 UTC by Abdellatif-E

2021-03-04 07:59 UTC, JanaKhanji requested changes

2021-03-04 07:59 UTC, JanaKhanji commented on src/Pages/CollectionPage/CollectionPage.js
> +        <div className="grid grid-cols-4  ">
add overflow-scroll to this in case there are more cards
and idk if you can do it with flex instead of grid

2021-03-04 07:59 UTC, JanaKhanji commented on src/Pages/CollectionPage/CollectionPage.js
> +            return <CollectionListItem number="2" type={el.type} />;
let the number here actually count the cards depending on the type from the data.js

2021-03-04 08:00 UTC, JanaKhanji requested changes

2021-03-04 08:00 UTC, JanaKhanji commented on src/Pages/CollectionPage/CollectionPage.js
> +    <div className="flex h-full bg-lightGrey">
remove this div since the bg-lightGrey is added to the page even without this 
add the flex class to the div bellow this

2021-03-04 17:28 UTC, JanaKhanji requested changes

2021-03-04 17:28 UTC, JanaKhanji commented on src/Pages/CollectionPage/CollectionPage.js
> +  count[collections[index].type.id - 1] =
change the id in the constant file so you don't need to write id -1

2021-03-07 13:09 UTC, osamaakb requested changes
- fix the cards showing like this
![image](https://user-images.githubusercontent.com/12795240/110240945-5afbbc80-7f5f-11eb-9fbc-acb378245357.png)
- the image or the girl should be more down the page
![image](https://user-images.githubusercontent.com/12795240/110240959-69e26f00-7f5f-11eb-97ce-01f3fca9b981.png)
- make the searching work
- make the cards filtering according to the category work

2021-03-07 13:10 UTC, osamaakb commented
Deadline: 9 March

2021-03-08 19:35 UTC, Abdellatif-E commented
Just discard or ignore this branch because I did not push it properly.

2021-03-08 19:35 UTC, closed without merging