Feat: Tracker page and about us button
Lebanon-WBC-Capstones/e-track-web pull request #76
Opened 2021-03-06 11:56 UTC by Nourcova

in this branch I created the Habit tracker page and  the "How it works" button in the Header now takes us to the about us section

2021-03-06 19:47 UTC, JanaKhanji requested changes

2021-03-06 19:47 UTC, JanaKhanji commented on src/Pages/TrackerPage/TrackerPage.js
> +          {/*<HabitTrackerItem title="Brushing teeth"  duration= {[ { id: 1, status: 'checked', date: 'Sat Feb 20 2021' },
remove this cmnt

2021-03-07 10:53 UTC, JanaKhanji requested changes

2021-03-07 10:53 UTC, JanaKhanji commented on src/Pages/TrackerPage/TrackerPage.js
> +          <div className=" bg-primary rounded-full w-7 h-7 m-2">
make this a button and add onclick to add functionality later

2021-03-07 10:53 UTC, JanaKhanji commented on src/Pages/TrackerPage/TrackerPage.js
> +          <div className=" bg-gray-300 rounded-full w-7 h-7 m-2 mx-28">
same here

2021-03-07 12:59 UTC, osamaakb commented
@Nourcova please fix the requested changes here

2021-03-08 06:59 UTC, osamaakb commented
there is some padding here, remove it so the list is aligned on the left with the header
![image](https://user-images.githubusercontent.com/12795240/110285816-e07d7c00-7ff4-11eb-82e0-6e774a3d7c9a.png)

2021-03-08 06:59 UTC, osamaakb commented
make this space between so the search bar goes to the most left and the buttons to the most right
![image](https://user-images.githubusercontent.com/12795240/110285894-01de6800-7ff5-11eb-96c9-4f10ebebb3f0.png)

2021-03-08 07:00 UTC, osamaakb commented
Please add the functionality to this page too

2021-03-10 17:49 UTC, osamaakb commented
please fix the conflicts and the netlify errors

2021-03-10 17:55 UTC, osamaakb commented on src/Pages/HomePage/Header/Header.js
> +function Header({ func }) {
what's this `func` here

2021-03-11 10:10 UTC, osamaakb approved these changes

2021-03-11 10:10 UTC, merged